### ISSUE TITLE
app carshed 

### ISSUE THREAD

**Issue by badrdev44** [cloud-annotations/object-detection-android#3]
Hello guys , im Beginner in devlopment , i make android wallpaper with Android studio , but when i want try the app in my phone is not working and crashed , i go in android studio Logcat , i see this erore :

2020-03-13 11:35:52.402 31155-31155/com.example.wallpaper1 E/mple.wallpaper: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2020-03-13 11:35:52.405 31155-31155/com.example.wallpaper1 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.wallpaper1, PID: 31155
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.wallpaper1/com.example.wallpaper1.MainActivity}: java.lang.SecurityException: read wallpaper: Neither user 10195 nor current process has android.permission.READ_EXTERNAL_STORAGE.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.SecurityException: read wallpaper: Neither user 10195 nor current process has android.permission.READ_EXTERNAL_STORAGE.
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.app.IWallpaperManager$Stub$Proxy.getWallpaper(IWallpaperManager.java:566)
        at android.app.WallpaperManager$Globals.getCurrentWallpaperLocked(WallpaperManager.java:497)
        at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:434)
        at android.app.WallpaperManager$Globals.peekWallpaperBitmap(WallpaperManager.java:411)
        at android.app.WallpaperManager.getDrawable(WallpaperManager.java:801)
        at com.example.wallpaper1.MainActivity.UpdateMyWallpaper(MainActivity.java:51)
        at com.example.wallpaper1.MainActivity.onCreate(MainActivity.java:45)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(ContextImpl.java:2046)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2074)
        at com.android.server.wallpaper.WallpaperManagerService.enforceCallingOrSelfPermissionAndAppOp(WallpaperManagerService.java:1990)
        at com.android.server.wallpaper.WallpaperManagerService.getWallpaper(WallpaperManagerService.java:2008)
        at android.app.IWallpaperManager$Stub.onTransact(IWallpaperManager.java:134)
<img width="1280" alt="Capture d’écran 2020-03-13 à 12 42 08" src="https://user-images.githubusercontent.com/50301086/76618320-9ae4bb00-6528-11ea-9f4d-52577cbd9637.png">

please help me & thanks :)

**Comment by bourdakos1** [comment]
It looks like the error is a ` READ_EXTERNAL_STORAGE` permission error. Make sure the app has the proper permissions in settings
